version: '3.5'
services:
    backend:
        container_name: ${COMPOSE_PROJECT_NAME}_backend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
                USER_NAME: ${CONTAINER_USER}
        expose:
            - 80
        volumes:
            - ${PROJECTFOLDER}:/var/www/html/
        working_dir: /var/www/html/
        user: ${CONTAINER_USER}
        networks:
            - gaia
    # Servicio de mysql
    db:
        image: mysql:5.7
        container_name: ${COMPOSE_PROJECT_NAME}_db
        volumes:
            - ${DB_BACKUP_FOLDER}:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        restart: unless-stopped
        networks:
            - gaia
    # Servicio de phpmyadmin. Se accede a él usando la ruta localhost:puerto
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ABSOLUTE_URI: https://gaia.manizales.unal.edu.co/encuesta_esppb_phpmyadmin/
        expose:
            - 80
        networks:
            - gaia
networks:
    backend:
        name: ${COMPOSE_PROJECT_NAME}_backend
    gaia:
        name: gaia
        external: true
